version: '3.7'
services:
  ide:
    build: .
    ports:
      - "8020:8080"
      - "9000:9000"
    volumes:
        - type: bind
          source: ./data
          target: /data
        - type: bind
          source: ./code
          target: /code
