version: '3.7'
services:
  ide:
    image: patrickalaspaa/vscode-ide:latest
    ports:
      - "8080:8080"
    volumes:
        - type: bind
          source: ./data
          target: /data
        - type: bind
          source: ./code
          target: /code
